//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   About &quot;microsoft-edge&quot; Scheme に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutEdgeScheme {
            get {
                return ResourceManager.GetString("AboutEdgeScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About Redirect Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutRedirectSetting {
            get {
                return ResourceManager.GetString("AboutRedirectSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About This App に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutThisApp {
            get {
                return ResourceManager.GetString("AboutThisApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AddRedirect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddRedirect {
            get {
                return ResourceManager.GetString("AddRedirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RedirectToDefaultBrowser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Redirect to Default Browser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppName_SP {
            get {
                return ResourceManager.GetString("AppName_SP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copied! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Copied {
            get {
                return ResourceManager.GetString("Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy To Clipboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to copy the URL to the Clipboard? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CopyURL {
            get {
                return ResourceManager.GetString("CopyURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Developed by Jukusui💤 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Don&apos;t Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DontSave {
            get {
                return ResourceManager.GetString("DontSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can reorder redirects by drag &amp; drop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DragAndDropReorder {
            get {
                return ResourceManager.GetString("DragAndDropReorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EditRedirect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditRedirect {
            get {
                return ResourceManager.GetString("EditRedirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error has occurred に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExceptionOccurred {
            get {
                return ResourceManager.GetString("ExceptionOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Feedback に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   History に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input Pattern に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input pattern using Regular Expression に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputPlaceholder {
            get {
                return ResourceManager.GetString("InputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last URI に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LastURI {
            get {
                return ResourceManager.GetString("LastURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last URL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LastURL {
            get {
                return ResourceManager.GetString("LastURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you close the window before save the setting, it will be discarded に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoticeCloseText {
            get {
                return ResourceManager.GetString("NoticeCloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are You Sure Discarding Changes? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoticeMove {
            get {
                return ResourceManager.GetString("NoticeMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Will You Save Your Changes? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoticeSave {
            get {
                return ResourceManager.GetString("NoticeSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you continue to move, the changes will be discarded に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoticeSaveText {
            get {
                return ResourceManager.GetString("NoticeSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OFF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ON に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open With Default Browser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenWithDefaultBrowser {
            get {
                return ResourceManager.GetString("OpenWithDefaultBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open With MS Edge に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenWithEdge {
            get {
                return ResourceManager.GetString("OpenWithEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output Pattern に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output pattern using Regular Expression に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OutputPlaceholder {
            get {
                return ResourceManager.GetString("OutputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recognized URL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RecognizedURL {
            get {
                return ResourceManager.GetString("RecognizedURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Redirect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Redirect {
            get {
                return ResourceManager.GetString("Redirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Test of Redirect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RedirectTest {
            get {
                return ResourceManager.GetString("RedirectTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Example of Redirect Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RegExExample {
            get {
                return ResourceManager.GetString("RegExExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Additional Info of RegEx に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RegExInfo {
            get {
                return ResourceManager.GetString("RegExInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restore に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Browser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectBrowser {
            get {
                return ResourceManager.GetString("SelectBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select MS Edge に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectEdge {
            get {
                return ResourceManager.GetString("SelectEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   When Encountered Issue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SomeProblem {
            get {
                return ResourceManager.GetString("SomeProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Store に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Test Input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace target URL that starts with http or https に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TestInputPlaceholder {
            get {
                return ResourceManager.GetString("TestInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replaced URL that starts with http or https に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TestOutputPlaceholder {
            get {
                return ResourceManager.GetString("TestOutputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tips に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Identifiable free name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitlePlaceholder {
            get {
                return ResourceManager.GetString("TitlePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Turn OFF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TurnOff {
            get {
                return ResourceManager.GetString("TurnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Turn ON に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TurnOn {
            get {
                return ResourceManager.GetString("TurnOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting of URL Redirect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UrlRedirectSetting {
            get {
                return ResourceManager.GetString("UrlRedirectSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Used RegExes For Redirects に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UsedRegExesForRedirects {
            get {
                return ResourceManager.GetString("UsedRegExesForRedirects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Web Page に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebPage {
            get {
                return ResourceManager.GetString("WebPage", resourceCulture);
            }
        }
    }
}
