//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UniversalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UniversalResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Properties.UniversalResources", typeof(UniversalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Jukusui に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jukusui💤 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AuthorWithEmoji {
            get {
                return ResourceManager.GetString("AuthorWithEmoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Feedback Hub に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FeedbackHub {
            get {
                return ResourceManager.GetString("FeedbackHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   feedback-hub: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FeedbackHubUri {
            get {
                return ResourceManager.GetString("FeedbackHubUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GitHub に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GitHub {
            get {
                return ResourceManager.GetString("GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://github.com/jukusui/RedirectToDefaultBrowser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GitHubUri {
            get {
                return ResourceManager.GetString("GitHubUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mastodon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mastodon {
            get {
                return ResourceManager.GetString("Mastodon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @jukusui@mstdn.jp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MastodonName {
            get {
                return ResourceManager.GetString("MastodonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://mstdn.jp/@jukusui に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MastodonUri {
            get {
                return ResourceManager.GetString("MastodonUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Microsoft Store に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSStore {
            get {
                return ResourceManager.GetString("MSStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://www.jukusui.net/Product/R2DB/ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string R2DBUri {
            get {
                return ResourceManager.GetString("R2DBUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ms-windows-store://pdp/?ProductId=9N86NDB1C3MP に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoreUri {
            get {
                return ResourceManager.GetString("StoreUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Twitter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @jukusui_zzz に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TwitterName {
            get {
                return ResourceManager.GetString("TwitterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://twitter.com/jukusui_zzz に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TwitterUri {
            get {
                return ResourceManager.GetString("TwitterUri", resourceCulture);
            }
        }
    }
}
