//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IfeoBootstrap.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IfeoBootstrap.Properties.ExResources", typeof(ExResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Redirect App is not Exist.
        ///Would you like to open Store Page? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AppMissing {
            get {
                return ResourceManager.GetString("AppMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Argument&apos;s file is not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ArgFileNotFound {
            get {
                return ResourceManager.GetString("ArgFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MS Edge&apos;s link is not exist.
        ///Please reInstall R2DB IFEO. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EdgeMissing {
            get {
                return ResourceManager.GetString("EdgeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Missing arguments. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MissingArgs {
            get {
                return ResourceManager.GetString("MissingArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No arguments. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoArgs {
            get {
                return ResourceManager.GetString("NoArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnhandledCaption {
            get {
                return ResourceManager.GetString("UnhandledCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown Arguments. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnknownArgs {
            get {
                return ResourceManager.GetString("UnknownArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The call is from an app without pre-registration. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnknownIfeoSource {
            get {
                return ResourceManager.GetString("UnknownIfeoSource", resourceCulture);
            }
        }
    }
}
